# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23fd5106216a4f3c6241a0ac1607421586a05b02eab46c3efca2f36ef032375f4ade72d069b9d73db2aeb472b76fc8686563dbfa8036dc63bd6db957b7fb238c

test:
  secret_key_base: b91ddad7994357ebb16a0c212d611db54619460bbe3e42e83f489afef3d9e447f509c4c5387d8041ebcf915f25ee6e6494f0e0b2b35debbe6405e8a77853dd84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
